apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80
            # - port: 4000
            #   targetPort: 80
          env:
            - name: HELLO
              value: hello
