# to make it work locally
# https://kubernetes.github.io/ingress-nginx/deploy/#docker-desktop
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
    # - host: <Host> # domain-based-routing
    - http:
        paths:
          - pathType: Prefix
            path: "/" # path-based-routing
            backend:
              service:
                name: myservice
                port:
                  number: 80
